### ISSUE TITLE
ImportError: No module named backports.functools_lru_cache

### ISSUE THREAD

**Issue by NanoWireDnB** [Razzeee/script.module.arrow#2]
Hi,
script.module.arrow\lib\arrow\parser.py is throwing an error that the python module "backports.functools_lru_cache" could not be found.
Had the error with Kodi 18.1 and now with 18.5

> 2019-12-14 17:23:44.163 T:7024  NOTICE: Starting Kodi (18.5 Git:20191116-37f51f6e63). Platform: Windows NT x86 64-bit
> 2019-12-14 17:23:44.163 T:7024  NOTICE: Using Release Kodi x64 build
> 2019-12-14 17:23:44.163 T:7024  NOTICE: Kodi compiled 2019-11-16 by MSVC 191627034 for Windows NT x86 64-bit version 10.0 (0x0A000006)
> 2019-12-14 17:23:44.163 T:7024  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18362

I'm using the latest version of script.module.arrow which should be 0.15.4. The issue existed also with 0.12.1

Part of the log with the python callback:

`2019-12-14 17:23:57.542 T:11640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named backports.functools_lru_cache
                                            Traceback (most recent call last):
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\plugin.py", line 9, in <module>
                                                import main
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\resources\lib\main.py", line 17, in <module>
                                                from metadatautils import MetadataUtils
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\metadatautils.py", line 9, in <module>
                                                import helpers.kodi_constants as kodi_constants
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\kodi_constants.py", line 9, in <module>
                                                from utils import KODI_VERSION
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\utils.py", line 13, in <module>
                                                import arrow
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\__init__.py", line 3, in <module>
                                                from .api import get, now, utcnow
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\api.py", line 10, in <module>
                                                from arrow.factory import ArrowFactory
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\factory.py", line 18, in <module>
                                                from arrow import parser
                                              File "C:\Users\KODI\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\parser.py", line 15, in <module>
                                                from backports.functools_lru_cache import lru_cache  # pragma: no cover
                                            ImportError: No module named backports.functools_lru_cache
                                            -->End of Python script error report<--`

Because python is integrated in Kodi I cannot run a fix, which seems to work with normal python installations:
https://stackoverflow.com/questions/47179433/python-2-7-functools-lru-cache-does-not-import-although-installed

Maybe you have an idea how to solve this issue?
Thanks in advance.

BR Nano

**Comment by NanoWireDnB** [comment]
BTW using your old version 0.10.0 with an old version of arrow seems to be a workaround:
https://github.com/Razzeee/script.module.arrow/tree/e23cc1496d17ddb9231af3632b14625bd3579010

**Comment by ondrejbima** [comment]
https://mirrors.kodi.tv/addons/krypton/script.module.arrow/script.module.arrow-0.10.0.zip

**Comment by matthuisman** [comment]
@Razzeee 
Broken a lot of my addons :(
Was this tested before pushing update??

I've done a post here on how-to downgrade as a temp fix:
https://www.matthuisman.nz/2019/12/kodi-fix-arrow-module-error.html

**Comment by razzeee** [comment]
Fix should be available as soon as the server updates. Thanks for mentioning that 0.15.4 also is broken, as it tested fine with python 3 (obviously)

**Comment by matthuisman** [comment]
@Razzeee 
Thank you.
I can confirm 0.15.5 fixes it.

https://mirrors.kodi.tv/addons/krypton/script.module.arrow/script.module.arrow-0.15.5.zip

**Comment by DataBass504** [comment]
Updated to 0.15.5 directly, add-ons not working now.

**Comment by razzeee** [comment]
Can you be more specific?

**Comment by DataBass504** [comment]
It appears I don't have backports script installed, Kodi repository doesn't provide a update for it or have it inside their repository even.

**Comment by razzeee** [comment]
It does have it, check the mirror 
http://ftp.snt.utwente.nl/pub/software/xbmc/addons/krypton/addons.xml
http://ftp.snt.utwente.nl/pub/software/xbmc/addons/leia/addons.xml
http://ftp.snt.utwente.nl/pub/software/xbmc/addons/matrix/addons.xml

Keep in mind that the referenced dependency version is just a lower border.
