### ISSUE TITLE
Errors in Windows O.S.

### ISSUE THREAD

**Issue by manfeed** [Razzeee/script.module.arrow#4]
Hi! Thanks for your work in this script! I’m a Kodi skinner and make use of an addon named script.embuary.info in my skin Aeon Tajo. This addon uses your module and it keeps throwing errors as follows…

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <class 'AttributeError'>
 Error Contents: 'datetime.timedelta' object has no attribute 'timestamp'
 Traceback (most recent call last):
   File "C:\Matrix2\portable_data\addons\script.embuary.info\plugin.py", line 5, in <module>
     from resources.lib.widgets import *
   File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\widgets.py", line 11, in <module>
     from resources.lib.helper import *
   File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\helper.py", line 15, in <module>
     import arrow
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
     from .api import get, now, utcnow
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
     from arrow.arrow import TZ_EXPR, Arrow
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 34, in <module>
     from arrow import formatter, locales, parser, util
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\parser.py", line 26, in <module>
     from arrow.util import next_weekday, normalize_timestamp
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\util.py", line 6, in <module>
     from arrow.constants import (
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\constants.py", line 16, in <module>
     _MAX_TIMESTAMP = datetime.max.timestamp()
 AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'
 -->End of Python script error report<--

  INFO <general>: Python interpreter stopped
  INFO <general>: initializing python engine.
  ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <class 'AttributeError'>
 Error Contents: 'datetime.timedelta' object has no attribute 'tzinfo'
 Traceback (most recent call last):
   File "C:\Matrix2\portable_data\addons\script.embuary.info\plugin.py", line 5, in <module>
     from resources.lib.widgets import *
   File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\widgets.py", line 11, in <module>
     from resources.lib.helper import *
   File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\helper.py", line 15, in <module>
     import arrow
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
     from .api import get, now, utcnow
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
     from arrow.arrow import TZ_EXPR, Arrow
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 1703, in <module>
     Arrow.min = Arrow.fromdatetime(dt_datetime.min)
   File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 318, in fromdatetime
     if dt.tzinfo is None:
 AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'
 -->End of Python script error report<--

…I told it to embuary’s author, but it says there’s nothing he can do. The funny thing is that some users using Linux or Android say that they have no errors, but Windows users like myself do…

Thanks in advance for your help!

**Comment by razzeee** [comment]
You might want to look at https://github.com/xbmc/xbmc/issues/17311 and check which version you end up running

**Comment by manfeed** [comment]
Thanks for your quick answer!
version="1.0.3.1"

**Comment by manfeed** [comment]
One user in the Kodi Forum told me:

Can you try to change constants.py in script.module.arrow and test....mine is Kodi on windows 64
(My PC have no errors in log - Error Contents: 'datetime.timedelta' object has no attribute 'timestamp')

[constants.txt](https://github.com/razzeee/script.module.arrow/files/8145451/constants.txt)


...I tested with it and I have much fewer errors (though I still have them), and, in addition, I don't know if it breaks something and I still haven't noticed...

**Comment by thezoggy** [comment]
just had this happened on 1.0.3.1 with kodi 19.4 on win10
```
2022-06-29 17:05:34.881 T:11668    INFO <general>: Starting Kodi (19.4 (19.4.0) Git:20220302-e12e66e019). Platform: Windows NT x86 64-bit
2022-06-29 17:05:34.881 T:11668    INFO <general>: Using Release Kodi x64
2022-06-29 17:05:34.881 T:11668    INFO <general>: Kodi compiled 2022-03-03 by MSVC 191627045 for Windows NT x86 64-bit version 10.0 (0x0A000007)
2022-06-29 17:05:34.881 T:11668    INFO <general>: Running on Windows 10 21H2, kernel: Windows NT x86 64-bit version 10.0.19044.1766
2022-06-29 17:05:34.881 T:11668    INFO <general>: FFmpeg version/source: 4.3.2-Kodi
2022-06-29 17:05:34.882 T:11668    INFO <general>: Host CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 8 cores available
2022-06-29 17:05:34.882 T:11668    INFO <general>: System has 16.0 GB of RAM installed
...
2022-06-29 17:05:34.970 T:11668    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: script.module.arrow v1.0.3.1 installed
2022-06-29 17:05:34.968 T:11668    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: metadata.tvdb.com.python v1.0.3 installed
```
```
2022-06-29 17:06:45.091 T:12848   DEBUG <general>: CPythonInvoker(3, C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\scraper.py): instantiating addon using automatically obtained id of "metadata.tvdb.com.python" dependent on version 3.0.0 of the xbmc.python api
2022-06-29 17:06:45.598 T:12848   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'bytes' object has no attribute 'tzinfo'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\scraper.py", line 3, in <module>
                                                       from resources.lib import actions
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\resources\lib\actions.py", line 14, in <module>
                                                       from . import episodes, series
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\resources\lib\episodes.py", line 10, in <module>
                                                       from .nfo import parse_episode_guide_url
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\resources\lib\nfo.py", line 7, in <module>
                                                       from . import series
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\resources\lib\series.py", line 11, in <module>
                                                       from .ratings import ratings
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\resources\lib\ratings.py", line 6, in <module>
                                                       from .trakt_rating import get_trakt_rating_and_votes
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\metadata.tvdb.com.python\resources\lib\trakt_rating.py", line 4, in <module>
                                                       from trakt import Trakt
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\__init__.py", line 3, in <module>
                                                       from trakt.client import TraktClient
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\client.py", line 3, in <module>
                                                       from trakt.core.configuration import ConfigurationManager
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\configuration.py", line 3, in <module>
                                                       from trakt.core.context_collection import ContextCollection
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\context_collection.py", line 3, in <module>
                                                       from trakt.core.helpers import synchronized
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\helpers.py", line 9, in <module>
                                                       import arrow
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 1703, in <module>
                                                       Arrow.min = Arrow.fromdatetime(dt_datetime.min)
                                                     File "C:\Users\zoggy\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 318, in fromdatetime
                                                       if dt.tzinfo is None:
                                                   AttributeError: 'bytes' object has no attribute 'tzinfo'
                                                   -->End of Python script error report<--
```

trying to refresh a series it crapped out and removed it. then tried again another time and it magically worked and updated. seems intermittent when tzinfo will be none within the addon

**Comment by manfeed** [comment]
The closest to a 'fix' that I could get is this:
[script.module.arrow.zip](https://github.com/razzeee/script.module.arrow/files/12542658/script.module.arrow.zip)
